[project]
authors = ["Jesse Akes <akesjesse@gmail.com>"]
channels = ["conda-forge"]
description = "Analysis of Meterological data in the Skagit River Basin"
name = "skagit-met"
platforms = ["osx-arm64", "linux-64", "osx-64"]
version = "0.1.0"

[feature.data-download.tasks]
hrrr = "python scripts/hrrr_downloader.py"
wrf = "python scripts/wrf_downloader.py"
prism = "python scripts/prism_downloader.py"
ornl = "python scripts/ornl_downloader.py"
snotel = "python scripts/snotel_downloader.py"
# Same as notebooks/HRRR_Downloader.py
hrrr-test = "python scripts/hrrr_downloader.py --parameters 'TMP:surface,RH:2 m above ground,WIND:10 m above ground,APCP:surface:0-1 hour acc fcst,DSWRF:surface,DLWRF:surface' --startDate 2020-03-01 --endDate 2020-03-02"

[feature.analysis.tasks]
nb = "jupyter lab"

[environments]
data-download = {features = ["data-download"], no-default-feature = true}
analysis = ["analysis"]

[feature.data-download.dependencies]
python = "3.10.*"
herbie-data = "*"
wgrib2 = "*"
geojson = "*"
zarr = "*"
pygrib = "*"
cfgrib = "*"
dask = "*"
flox = "*"
xarray = "*"
boto3 = "*"
netcdf4 = "*"
geopandas = ">=0.9.0,<1.0.0"
numpy = "*"
rioxarray = "*"
fsspec = "*"
libgdal-netcdf = ">=3.10.2,<4"
requests = ">=2.32.3,<3"
aiohttp = ">=3.11.18,<4"
# To use demo notebooks
ipykernel = "*"

[feature.data-download.target.osx-arm64.dependencies]
libgfortran5 = ">=14"

[feature.data-download.pypi-dependencies]
metloom = "*"

[feature.analysis.dependencies]
python = "3.11.*"
ipykernel = "*"
cartopy = "*"
zarr = "*"
dask = "*"
flox = "*"
xarray = "*"
netcdf4 = "*"
xcdat = "*"
ipympl = "*"
contextily = "*"
pip = "*"
jupyterlab = "*"
pixi-kernel = "*"
rioxarray = "*"
virtualizarr = "*"
xoak = "*"
synopticpy = "*"
elevation = "*"
regionmask = "*"
geopandas = "*"
kerchunk = "*"
fastparquet = "*"
holoviews = "*"
hvplot = "*"
pandas = "*"
geoviews = ">=1.14.0,<2"
pint-xarray = ">=0.4,<0.5"
pygmt = ">=0.15.0,<0.16"
jupyter_bokeh = ">=4.0.5,<5"
ffmpeg = ">=7.1.1,<8"
pillow = ">=11.2.1,<12"
libgdal-netcdf = ">=3.10.3,<4"

[feature.analysis.target.osx-arm64.dependencies]
libgfortran5 = ">=14"

[feature.analysis.pypi-dependencies]
xarray-regrid = ">=0.4.0, <0.5"

[pypi-dependencies]
