[project]
authors = ["Scott Henderson <scottyhq@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "dshydro"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
ipykernel = ">=6.29.5,<7"
xarray = ">=2024.9.0,<2025"
h5netcdf = ">=1.3.0,<2"
fsspec = ">=2024.9.0,<2025"
aiohttp = ">=3.10.8,<4"
requests = ">=2.32.3,<3"
# virtualizarr = ">=1.0.0,<2"
fastparquet = ">=2024.5.0,<2025"
kerchunk = ">=0.2.6,<0.3"
cftime = ">=1.6.4,<2"
matplotlib = ">=3.9.2,<4"

[pypi-dependencies]
virtualizarr = { git = "https://github.com/zarr-developers/VirtualiZarr.git", rev = "main" }
