[project]
authors = ["Jesse Akes <akesjesse@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "skagit-met"
platforms = ["osx-arm64", "linux-64", "osx-64"]
version = "0.1.0"

[tasks]
nb = "jupyter lab"
hrr = "python scripts/hrrr_downloader.py"
wrf = "python scripts/wrf_downloader.py"
prism = "python scripts/prism_downloader.py"
ornl = "python scripts/ornl_downloader.py"
snotel = "python scripts/snotel_downloader.py"

[dependencies]
python = "3.10.*"
herbie-data = "*"
ipykernel = "*"
cartopy = "*"
wgrib2 = "*"
geojson = "*"
zarr = "*"
pygrib = "*"
cfgrib = "*"
dask = "*"
flox = "*"
xarray = "*"
boto3 = "*"
netcdf4 = "*"
metpy = "*"
xcdat = "*"
ipympl = "*"
contextily = "*"
pip = "*"
jupyterlab = ">=4.2.5,<5"
pixi-kernel = ">=0.5.1,<0.6"
rioxarray = ">=0.17.0,<0.18"
virtualizarr = ">=1.0.0,<2"
xoak = ">=0.1.1,<0.2"
synopticpy = ">=2024.9.0,<2025"
elevation = ">=1.1.3,<2"
regionmask = "*"
geopandas = ">=0.9.0,<1.0.0"
requests = ">=2.32.3,<3"
aiohttp = ">=3.11.7,<4"
fsspec = '==2024.9.0'
s3fs = '>=2022.11'
earthaccess = '>=0.9.0'
holoviews = ">=1.20.0,<2"

[pypi-dependencies]
metloom = "*"
folium = "*"
mapclassify = "*"
pyprismclimate = "*"
pre-commit = ">=4.0.1, <5"
