name: Test Download Scripts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # NOTE: macos-latest is ARM, macos-13 is Intel.
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v6

      - uses: prefix-dev/setup-pixi@v0.9.3
        with:
          environments: data-download
          cache: true
          frozen: true

      - name: Test HRRR Download
        run: |
          pixi run hrrr-test

      - name: Test WRF Download
        run: |
          pixi run wrf-test

      - name: Test ORNL Download
        run: |
          pixi run ornl-test

      - name: Test PRISM Download
        run: |
          pixi run prism-test

      - name: Test SNOTEL Download
        run: |
          pixi run snotel-test

      - name: Inspect download directory
        run: |
          du -sh data/weather_data/*

